services:
  container-dev:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    user: www-data
    container_name: container-dev
    volumes:
      - .:/var/www/html
    tty: true
